services:
  web:
    image: nginx:1.28.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./app:/app
    networks:
      - phpmarine-network
    depends_on:
      - php
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    ports:
      - "9003:9003"
    volumes:
      - ./app:/app
    networks:
      - phpmarine-network
    depends_on:
      mysql:
        condition: service_healthy
      mailpit:
        condition: service_started
    environment:
      - XDEBUG_MODE=develop
    restart: unless-stopped

  mysql:
    image: mariadb:10.11.13
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - phpmarine-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5