services:
  web:
    image: nginx:1.28.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./app:/app
    networks:
      - phpmarine-network
    depends_on:
      - php
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    ports:
      - "9003:9003"
    volumes:
      - ./app:/app
    networks:
      - phpmarine-network
    depends_on:
      mysql:
        condition: service_healthy
      mailpit:
        condition: service_started
    environment:
      - XDEBUG_MODE=develop
    restart: unless-stopped